name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@latest

      - name: setup node
        uses: actions/setup-node@latest
        with:
          node-version: "18.x"

      - name: install dependencies
        run: npm ci

      - name: build
        run: yarn run export && touch ./out/.nojekyll

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: public
          FOLDER: out
