name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: install dependencies
        run: npm ci

      - name: build
        run: yarn run export && touch ./out/.nojekyll && cp CNAME ./out/CNAME

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
          folder: out
